image: python:3.12
services:
  - postgres:13

variables:
  DATABASE_URL: postgres://cnrprod1725726301-team-78213:cnrprod1725726301-team-78213@rc1b-5xmqy6bq501kls4m.mdb.yandexcloud.net:6432/cnrprod1725726301-team-78213

stages:
  - test
  - deploy

before_script:
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - python manage.py test

deploy:
  stage: deploy
  script:
    - docker build -t zadanie-6105-web .
    - docker push zadanie-6105-web
    - kubectl apply -f deployment.yaml
    - kubectl apply -f service.yaml