stages:
  - build
  - deploy


build:
  stage: build
  script:
    - docker-compose -f docker-compose.yml build
  only:
    - master

deploy:
  stage: deploy
  script:
   - docker-compose -f docker-compose.yml up -d
  only:
    - master