services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: cnrprod1725726301-team-78213
      POSTGRES_USER: cnrprod1725726301-team-78213
      POSTGRES_PASSWORD: cnrprod1725726301-team-78213
    ports:
      - "5432:5432"
  web:
    environment:
      - DATABASE_URL=postgres://cnrprod1725726301-team-78213:cnrprod1725726301-team-78213@rc1b-5xmqy6bq501kls4m.mdb.yandexcloud.net:6432/cnrprod1725726301-team-78213

    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./solution/avito_tender_service/avito_tender_service:/code
    ports:
      - "8080:8080"
    depends_on:
      - db