# Generated by Django 5.1.1 on 2024-09-09 19:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_remove_tender_organization_tender_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='serviceType',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='version',
        ),
        migrations.AddField(
            model_name='tender',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.employee'),
        ),
        migrations.AddField(
            model_name='tender',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.organization'),
        ),
        migrations.AddField(
            model_name='tender',
            name='service_type',
            field=models.CharField(choices=[('Construction', 'Construction'), ('IT', 'IT'), ('Logistics', 'Logistics')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('In Progress', 'In Progress')], max_length=20),
        ),
        migrations.CreateModel(
            name='OrganizationResponsible',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.employee')),
            ],
        ),
    ]
