# Generated by Django 5.1.1 on 2024-09-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_remove_tender_created_by_remove_tender_servicetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='version',
            field=models.IntegerField(null=True),
        ),
    ]
