# Generated by Django 5.1.1 on 2024-09-09 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0004_tender_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='version',
        ),
        migrations.CreateModel(
            name='TenderVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='tenders.tender')),
            ],
            options={
                'unique_together': {('tender', 'version')},
            },
        ),
    ]
