# Generated by Django 5.1.1 on 2024-09-10 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0006_bidversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidreview',
            old_name='review_text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='bidreview',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='bidreview',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='bidreview',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bidreview',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tenders.bid'),
        ),
    ]
